const express = require('express');
const router = express.Router({
  mergeParams: true
});
const List = require('../models/list');
const mongoose = require('mongoose');
const ObjectId = mongoose.Types.ObjectId;
const debug = require('debug')('demo:lists');
const utils = require('./utils');

// GET list of all lists
router.get('/', utils.authenticate, getList, function(req, res, next) {
  // Authorization
  if (req.currentUserId != req.params.userId) {
    return res.status(403).send("You can't see these lists")
  }
  // Find the lists
  List
    .find({
      user: req.currentUserId
    })
    .populate('user')
    .populate('picture')
    .sort('name')
    .exec(function(err, lists) {
      if (err) {
        return next(err);
      }
      res.send(lists);
    });
});

/* GET one specific list */
router.get('/:listId', utils.authenticate, getList, function(req, res, next) {
  // Authorization
  if (req.currentUserId != req.params.userId || req.currentUserId != req.list.user) {
    return res.status(403).send("You can't see this list")
  }
  // Find the list
  res.send(req.list);
  List
    .find(req.list)
    .populate('user')
    .populate('picture')
    .exec(function(err, list) {
      if (err) {
        return next(err);
      }
      res.send(list);
    });
});


/**
 * @api {post} /users/id/lists Create a list
 * @apiName CreateList
 * @apiGroup List
 * @apiVersion 1.0.0
 * @apiDescription Create a new list.
 *
 * @apiUse ListInRequestBody
 * @apiUse ListInResponseBody
 * @apiSuccess (Response body) {String} id A unique identifier for the list generated by the server
 * 
 * @apiExample Example
 *     POST / HTTP/1.1
 *     Content-Type: application/json
 *
 *     {
 *       "name": "Vacances",
 *     }
 *
 * @apiSuccessExample 201 Created
 *     HTTP/1.1 201 Created
 *     Content-Type: application/json
 *     Location: https://odos-archioweb.herokuapp.com/5f981e64eeac3042b0e27b86
 *
 *     [{
 *        "picture":[],
 *        "public":true,
 *        "_id":"5f98321aabf23b2cfce0fe76",
 *        "name":"Vacances",
 *        "creationDate":"2020-10-27T14:43:38.484Z",
 *        "modificationDate":"2020-10-27T14:43:38.485Z",
 *        "user":{
 *                "_id":"5f981e64eeac3042b0e27b86",
 *                "username":"Pomme",
 *                "email":"gateau@gmail.com",
 *                "registrationDate":"2020-10-27T13:19:32.249Z","__v":0},"__v":0
 *      }]
 */
router.post('/', utils.authenticate, getList, function(req, res, next) {
  // Authorization
  if (req.currentUserId != req.params.userId) {
    return res.status(403).send("You can't create your list there")
  }
  // Retrieve the user ID from the URL.
  const user = req.params.userId;
  // res.send(req.params.userId);
  // Create list and send response...
  const newList = new List(req.body);
  newList.set('user', user);

  newList.save(function(err, savedList) {
    if (err) {
      return next(err);
    }

    debug(`New list "${savedList.name}"`);
    res.status(201).send(savedList);
  });
});


// PUT the name of a list
router.patch('/:listId', utils.authenticate, getList, function(req, res, next) {
  // Authorization
  if (req.currentUserId != req.params.userId || req.currentUserId != req.list.user) {
    return res.status(403).send("You can't edit this list")
  }
  // Update all properties (regardless of whether they are in the request body or not)
  if (req.body.name !== undefined) {
    req.list.name = req.body.name;
  }

  if (req.body.public !== undefined) {
    req.list.public = req.body.public;
  }

  if (req.body.picture !== undefined) {
    req.list.picture.push(req.body.picture);
    // req.list.picture = req.body.picture;
  }

  req.list.modificationDate = new Date();

  req.list.save(function(err, savedList) {
    if (err) {
      return next(err);
    }

    debug(`Updated list "${savedList.name}"`);
    res.send(savedList);
  });
});


//DELETE one list
router.delete('/:listId', utils.authenticate, getList, function(req, res, next) {
  // Authorization
  if (req.currentUserId != req.params.userId || req.currentUserId != req.list.user) {
    return res.status(403).send("You can't delete this list")
  }
  // Delete the list
  req.list.remove(function(err) {
    if (err) {
      return next(err);
    }

    debug(`Deleted list "${req.list.name}"`);
    res.sendStatus(204);
  });
});

// Get the list by id
function getList(req, res, next) {
  // get the id of the list by the param
  const listId = req.params.listId;
  // if (!ObjectId.isValid(listId)) {
  //   return listNotFound(res, listId);
  // }
  // get the list by id
  List.findById(req.params.listId, function(err, list) {
    if (err) {
      return next(err);
    }
    // } else if (!list) {
    //   return listNotFound(res, listId);
    // }

    req.list = list;
    next();
  });
}


/**
 * @apiDefine ListIdInUrlPath
 * @apiParam (URL path parameters) {String} id The unique identifier of the list to retrieve
 */

/**
 * @apiDefine ListInRequestBody
 * @apiParam (Request body) {String} id An Id which is referencing the list (eg: `5f981e64eeac3042b0e27b86`)
 * @apiParam (Request body) {String{/^[a-zA-Z0-9]+$/}} username The username of the user (must be unique and cannot be blank)
 * @apiParam (Request body) {String{/\S+@\S+\.\S+/}} email The email of the user (must match an email form, must be unique and cannot be blank)
 * @apiParam (Request body) {String} password The password of the user that is put in hash (cannot be blank)
 */

/**
 * @apiDefine ListInResponseBody
 * @apiSuccess (Response body) {String} id An Id which is referencing the list 
 * @apiSuccess (Response body) {String{/^[a-zA-Z0-9]+$/}} username The username of the user 
 * @apiSuccess (Response body) {String{/\S+@\S+\.\S+/}} email The email of the user 
 * @apiSuccess (Response body) {String} registrationDate The date at which the user was created
 */

module.exports = router;
